# Generated by Django 4.1.3 on 2022-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('seats_number', models.IntegerField()),
                ('car_body', models.CharField(max_length=15)),
                ('engine_volume', models.FloatField()),
            ],
        ),
    ]
