# Generated by Django 4.1.3 on 2022-11-30 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
        ('cars', '0002_alter_carmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='auto_park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cars', to='auto_parks.autoparkmodel'),
        ),
    ]
