# Generated by Django 4.1.3 on 2022-12-04 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmodel_auto_park_alter_carmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='body',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine_volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
