# Generated by Django 4.1.4 on 2022-12-11 10:30

from django.db import migrations, models

import apps.cars.services


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_body_alter_carmodel_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.cars.services.upload_photo),
        ),
    ]
